FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./apps/http-server ./apps/http-server

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN pnpm install
RUN pnpm generate:db

EXPOSE 8080

CMD [ "pnpm", "start:backend"]