FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./apps/fe ./apps/fe

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN pnpm install
RUN pnpm generate:db
RUN DATABASE_URL=${DATABASE_URL} pnpm build

EXPOSE 3000

CMD [ "pnpm", "start:frontend"]